//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherAppServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CitiesStub
    {
        public int Id { get; set; }
        public string Request { get; set; }
        public string Response { get; set; }
        public System.DateTime CreateDate { get; set; }
        public CitiesStub()
        {

        }

        public CitiesStub(string request, string response)
        {
            this.Request = request;
            this.Response = response;
            this.CreateDate = DateTime.Now;
        }
    }
}
