//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherAppServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CitiesWeather
    {
        public int Id { get; set; }
        public string CityKey { get; set; }
        public double TemperatureValue { get; set; }
        public string WeatherText { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public CitiesWeather()
        {

        }

        public CitiesWeather(string cityKey, double temperatureValue, string weatherText)
        {
            this.CityKey = cityKey;
            this.TemperatureValue = temperatureValue;
            this.WeatherText = weatherText;
            this.UpdateDate = DateTime.Now;

        }
    }
}
