//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherAppServer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WeatherAppEntities : DbContext
    {
        public WeatherAppEntities()
            : base("name=WeatherAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CitiesStub> CitiesStub { get; set; }
        public virtual DbSet<CitiesWeather> CitiesWeather { get; set; }
        public virtual DbSet<CitiesFavorites> CitiesFavorites { get; set; }
    }
}
